In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
path=r"SalaryData_Test.csv"
df1=pd.read_csv(path)
df1

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [3]:
df1.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [5]:
df1.dtypes

age               int64
workclass        object
education        object
educationno       int64
maritalstatus    object
occupation       object
relationship     object
race             object
sex              object
capitalgain       int64
capitalloss       int64
hoursperweek      int64
native           object
Salary           object
dtype: object

In [6]:
df1['workclass'].unique()

array([' Private', ' Local-gov', ' Self-emp-not-inc', ' Federal-gov',
       ' State-gov', ' Self-emp-inc', ' Without-pay'], dtype=object)

In [7]:
df1['workclass']=df1['workclass'].map({' Private':0, ' Local-gov':1, ' Self-emp-not-inc':2, ' Federal-gov':3,
       ' State-gov':4, ' Self-emp-inc':5, ' Without-pay':6}).astype(int)

In [8]:
df1['education'].unique()

array([' 11th', ' HS-grad', ' Assoc-acdm', ' Some-college', ' 10th',
       ' Prof-school', ' 7th-8th', ' Bachelors', ' Masters', ' 5th-6th',
       ' Assoc-voc', ' 9th', ' Doctorate', ' 12th', ' 1st-4th',
       ' Preschool'], dtype=object)

In [9]:
df1['education']=df1['education'].map({' 11th':0, ' HS-grad':1, ' Assoc-acdm':2, ' Some-college':3, ' 10th':4,
       ' Prof-school':5, ' 7th-8th':6, ' Bachelors':7, ' Masters':8, ' 5th-6th':9,
       ' Assoc-voc':10, ' 9th':11, ' Doctorate':12, ' 12th':13, ' 1st-4th':14,
       ' Preschool':15}).astype(int)

In [10]:
df1['maritalstatus'].unique()

array([' Never-married', ' Married-civ-spouse', ' Widowed', ' Separated',
       ' Divorced', ' Married-spouse-absent', ' Married-AF-spouse'],
      dtype=object)

In [11]:
df1['maritalstatus']=df1['maritalstatus'].map({' Never-married':0, ' Married-civ-spouse':1, ' Widowed':2, ' Separated':3,
       ' Divorced':4, ' Married-spouse-absent':5, ' Married-AF-spouse':6}).astype(int)

In [12]:
df1['occupation'].unique()

array([' Machine-op-inspct', ' Farming-fishing', ' Protective-serv',
       ' Other-service', ' Prof-specialty', ' Craft-repair',
       ' Adm-clerical', ' Exec-managerial', ' Tech-support', ' Sales',
       ' Priv-house-serv', ' Transport-moving', ' Handlers-cleaners',
       ' Armed-Forces'], dtype=object)

In [13]:
df1['occupation']=df1['occupation'].map({' Machine-op-inspct':0, ' Farming-fishing':1, ' Protective-serv':2,
       ' Other-service':3, ' Prof-specialty':4, ' Craft-repair':5,
       ' Adm-clerical':6, ' Exec-managerial':7, ' Tech-support':8, ' Sales':9,
       ' Priv-house-serv':10, ' Transport-moving':11, ' Handlers-cleaners':12,
       ' Armed-Forces':13}).astype(int)

In [14]:
df1['relationship'].unique()

array([' Own-child', ' Husband', ' Not-in-family', ' Unmarried', ' Wife',
       ' Other-relative'], dtype=object)

In [15]:
df1['relationship']=df1['relationship'].map({' Own-child':0, ' Husband':1, ' Not-in-family':2, ' Unmarried':3, ' Wife':4,
       ' Other-relative':5}).astype(int)

In [16]:
df1['race'].unique()

array([' Black', ' White', ' Other', ' Amer-Indian-Eskimo',
       ' Asian-Pac-Islander'], dtype=object)

In [17]:
df1['race']=df1['race'].map({' Black':0, ' White':1, ' Other':2, ' Amer-Indian-Eskimo':3,
       ' Asian-Pac-Islander':4}).astype(int)

In [18]:
df1['sex'].unique()

array([' Male', ' Female'], dtype=object)

In [19]:
df1['sex']=df1['sex'].map({' Male':0, ' Female':1}).astype(int)

In [20]:
df1['native'].unique()

array([' United-States', ' Peru', ' Guatemala', ' Mexico',
       ' Dominican-Republic', ' Ireland', ' Germany', ' Philippines',
       ' Thailand', ' Haiti', ' El-Salvador', ' Puerto-Rico', ' Vietnam',
       ' South', ' Columbia', ' Japan', ' India', ' Cambodia', ' Poland',
       ' Laos', ' England', ' Cuba', ' Taiwan', ' Italy', ' Canada',
       ' Portugal', ' China', ' Nicaragua', ' Honduras', ' Iran',
       ' Scotland', ' Jamaica', ' Ecuador', ' Yugoslavia', ' Hungary',
       ' Hong', ' Greece', ' Trinadad&Tobago',
       ' Outlying-US(Guam-USVI-etc)', ' France'], dtype=object)

In [21]:
df1['native']=df1['native'].map({' United-States':0, ' Peru':1, ' Guatemala':2, ' Mexico':3,
       ' Dominican-Republic':4, ' Ireland':5, ' Germany':6, ' Philippines':7,
       ' Thailand':8, ' Haiti':9, ' El-Salvador':10, ' Puerto-Rico':11, ' Vietnam':12,
       ' South':13, ' Columbia':14, ' Japan':15, ' India':16, ' Cambodia':17, ' Poland':18,
       ' Laos':19, ' England':20, ' Cuba':21, ' Taiwan':22, ' Italy':23, ' Canada':24,
       ' Portugal':25, ' China':26, ' Nicaragua':27, ' Honduras':28, ' Iran':29,
       ' Scotland':30, ' Jamaica':31, ' Ecuador':32, ' Yugoslavia':33, ' Hungary':34,
       ' Hong':35, ' Greece':36, ' Trinadad&Tobago':37,
       ' Outlying-US(Guam-USVI-etc)':38, ' France':39}).astype(int)

In [22]:
df1['Salary'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [23]:
df1['Salary']=df1['Salary'].map({' <=50K':0, ' >50K':1})

In [24]:
df1

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          0          0            7              0           0   
1       38          0          1            9              1           1   
2       28          1          2           12              1           2   
3       44          0          3           10              1           0   
4       34          0          4            6              0           3   
...    ...        ...        ...          ...            ...         ...   
15055   33          0          7           13              0           4   
15056   39          0          7           13              4           4   
15057   38          0          7           13              1           4   
15058   44          0          7           13              4           6   
15059   35          5          7           13              1           7   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 0     0    0            0            0            40   
1                 1     1    0            0            0            50   
2                 1     1    0            0            0            40   
3                 1     0    0         7688            0            40   
4                 2     1    0            0            0            30   
...             ...   ...  ...          ...          ...           ...   
15055             0     1    0            0            0            40   
15056             2     1    1            0            0            36   
15057             1     1    0            0            0            50   
15058             0     4    0         5455            0            40   
15059             1     1    0            0            0            60   

       native  Salary  
0           0       0  
1           0       0  
2           0       1  
3           0       1  
4           0       0  
...       ...     ...  
15055       0       0  
15056       0       0  
15057       0       0  
15058       0       0  
15059       0       1  

[15060 rows x 14 columns]

In [25]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [26]:
X=df1.iloc[:,:-1]
y=df1.iloc[:,-1]

In [27]:
print(X)

       age  workclass  education  educationno  maritalstatus  occupation  \
0       25          0          0            7              0           0   
1       38          0          1            9              1           1   
2       28          1          2           12              1           2   
3       44          0          3           10              1           0   
4       34          0          4            6              0           3   
...    ...        ...        ...          ...            ...         ...   
15055   33          0          7           13              0           4   
15056   39          0          7           13              4           4   
15057   38          0          7           13              1           4   
15058   44          0          7           13              4           6   
15059   35          5          7           13              1           7   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0     

In [28]:
print(y)

0        0
1        0
2        1
3        1
4        0
        ..
15055    0
15056    0
15057    0
15058    0
15059    1
Name: Salary, Length: 15060, dtype: int64


In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=34)

In [30]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(12048, 13)
(3012, 13)
(12048,)
(3012,)


In [31]:
classifier=SVC()

In [32]:
classifier.fit(X_train,y_train)

SVC()

In [33]:
scores=classifier.score(X_test,y_test)

In [34]:
print(scores)

0.8031208499335989


In [35]:
df2=df1.values

In [36]:
X=df2[:,:-1]

In [37]:
y=df2[:,-1]

In [38]:
print(X)

[[25  0  0 ...  0 40  0]
 [38  0  1 ...  0 50  0]
 [28  1  2 ...  0 40  0]
 ...
 [38  0  7 ...  0 50  0]
 [44  0  7 ...  0 40  0]
 [35  5  7 ...  0 60  0]]


In [39]:
print(y)

[0 0 1 ... 0 0 1]


In [40]:
classifier=SVC()

In [41]:
classifier.fit(X_train,y_train)

SVC()

In [42]:
scores=classifier.score(X_test,y_test)

In [43]:
print(scores)

0.8031208499335989
