In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix 

In [3]:
df1=pd.read_csv('/content/drive/MyDrive/DATASETS/forestfires (1).csv')

In [4]:
df1

month  day  FFMC    DMC  ...  monthnov  monthoct  monthsep  size_category
0     mar  fri  86.2   26.2  ...         0         0         0          small
1     oct  tue  90.6   35.4  ...         0         1         0          small
2     oct  sat  90.6   43.7  ...         0         1         0          small
3     mar  fri  91.7   33.3  ...         0         0         0          small
4     mar  sun  89.3   51.3  ...         0         0         0          small
..    ...  ...   ...    ...  ...       ...       ...       ...            ...
512   aug  sun  81.6   56.7  ...         0         0         0          large
513   aug  sun  81.6   56.7  ...         0         0         0          large
514   aug  sun  81.6   56.7  ...         0         0         0          large
515   aug  sat  94.4  146.0  ...         0         0         0          small
516   nov  tue  79.5    3.0  ...         1         0         0          small

[517 rows x 31 columns]

In [5]:
df1.isnull().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [6]:
df1.head()

month  day  FFMC   DMC  ...  monthnov  monthoct  monthsep  size_category
0   mar  fri  86.2  26.2  ...         0         0         0          small
1   oct  tue  90.6  35.4  ...         0         1         0          small
2   oct  sat  90.6  43.7  ...         0         1         0          small
3   mar  fri  91.7  33.3  ...         0         0         0          small
4   mar  sun  89.3  51.3  ...         0         0         0          small

[5 rows x 31 columns]

In [7]:
df1=df1.drop(['month','day'],axis=1,)

In [8]:
df1

FFMC    DMC     DC   ISI  ...  monthnov  monthoct  monthsep  size_category
0    86.2   26.2   94.3   5.1  ...         0         0         0          small
1    90.6   35.4  669.1   6.7  ...         0         1         0          small
2    90.6   43.7  686.9   6.7  ...         0         1         0          small
3    91.7   33.3   77.5   9.0  ...         0         0         0          small
4    89.3   51.3  102.2   9.6  ...         0         0         0          small
..    ...    ...    ...   ...  ...       ...       ...       ...            ...
512  81.6   56.7  665.6   1.9  ...         0         0         0          large
513  81.6   56.7  665.6   1.9  ...         0         0         0          large
514  81.6   56.7  665.6   1.9  ...         0         0         0          large
515  94.4  146.0  614.7  11.3  ...         0         0         0          small
516  79.5    3.0  106.7   1.1  ...         1         0         0          small

[517 rows x 29 columns]

In [9]:
df1.head()

FFMC   DMC     DC  ISI  ...  monthnov  monthoct  monthsep  size_category
0  86.2  26.2   94.3  5.1  ...         0         0         0          small
1  90.6  35.4  669.1  6.7  ...         0         1         0          small
2  90.6  43.7  686.9  6.7  ...         0         1         0          small
3  91.7  33.3   77.5  9.0  ...         0         0         0          small
4  89.3  51.3  102.2  9.6  ...         0         0         0          small

[5 rows x 29 columns]

In [10]:
size_category1=pd.get_dummies(df1['size_category'],drop_first=True)
size_category1

small
0        1
1        1
2        1
3        1
4        1
..     ...
512      0
513      0
514      0
515      1
516      1

[517 rows x 1 columns]

In [11]:
df1=df1.drop('size_category',axis=1)
df1

FFMC    DMC     DC   ISI  ...  monthmay  monthnov  monthoct  monthsep
0    86.2   26.2   94.3   5.1  ...         0         0         0         0
1    90.6   35.4  669.1   6.7  ...         0         0         1         0
2    90.6   43.7  686.9   6.7  ...         0         0         1         0
3    91.7   33.3   77.5   9.0  ...         0         0         0         0
4    89.3   51.3  102.2   9.6  ...         0         0         0         0
..    ...    ...    ...   ...  ...       ...       ...       ...       ...
512  81.6   56.7  665.6   1.9  ...         0         0         0         0
513  81.6   56.7  665.6   1.9  ...         0         0         0         0
514  81.6   56.7  665.6   1.9  ...         0         0         0         0
515  94.4  146.0  614.7  11.3  ...         0         0         0         0
516  79.5    3.0  106.7   1.1  ...         0         1         0         0

[517 rows x 28 columns]

In [12]:
df1=pd.concat([df1,size_category1],axis=1)
df1

FFMC    DMC     DC   ISI  ...  monthnov  monthoct  monthsep  small
0    86.2   26.2   94.3   5.1  ...         0         0         0      1
1    90.6   35.4  669.1   6.7  ...         0         1         0      1
2    90.6   43.7  686.9   6.7  ...         0         1         0      1
3    91.7   33.3   77.5   9.0  ...         0         0         0      1
4    89.3   51.3  102.2   9.6  ...         0         0         0      1
..    ...    ...    ...   ...  ...       ...       ...       ...    ...
512  81.6   56.7  665.6   1.9  ...         0         0         0      0
513  81.6   56.7  665.6   1.9  ...         0         0         0      0
514  81.6   56.7  665.6   1.9  ...         0         0         0      0
515  94.4  146.0  614.7  11.3  ...         0         0         0      1
516  79.5    3.0  106.7   1.1  ...         1         0         0      1

[517 rows x 29 columns]

In [13]:
X=df1.iloc[:,:-1]
y=df1.iloc[:,-1]

In [14]:
print(X)

     FFMC    DMC     DC   ISI  ...  monthmay  monthnov  monthoct  monthsep
0    86.2   26.2   94.3   5.1  ...         0         0         0         0
1    90.6   35.4  669.1   6.7  ...         0         0         1         0
2    90.6   43.7  686.9   6.7  ...         0         0         1         0
3    91.7   33.3   77.5   9.0  ...         0         0         0         0
4    89.3   51.3  102.2   9.6  ...         0         0         0         0
..    ...    ...    ...   ...  ...       ...       ...       ...       ...
512  81.6   56.7  665.6   1.9  ...         0         0         0         0
513  81.6   56.7  665.6   1.9  ...         0         0         0         0
514  81.6   56.7  665.6   1.9  ...         0         0         0         0
515  94.4  146.0  614.7  11.3  ...         0         0         0         0
516  79.5    3.0  106.7   1.1  ...         0         1         0         0

[517 rows x 28 columns]


In [15]:
y=df1.iloc[:,-1]

In [16]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
512    0
513    0
514    0
515    1
516    1
Name: small, Length: 517, dtype: uint8


In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=34)

In [18]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(413, 28)
(104, 28)
(413,)
(104,)


In [19]:
clf=SVC()

In [20]:
param_grid=[{'kernel':['poly'],'gamma':[100,50,5,10,0.5,0.1,0.01,20,30],'C':[15,14,13,12,11,10,0.1,0.001,0.0001]}]

In [21]:
gsv=GridSearchCV(clf,param_grid,cv=10)

In [22]:
gsv

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001, 0.0001],
                          'gamma': [100, 50, 5, 10, 0.5, 0.1, 0.01, 20, 30],
                          'kernel': ['poly']}])

In [23]:
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001, 0.0001],
                          'gamma': [100, 50, 5, 10, 0.5, 0.1, 0.01, 20, 30],
                          'kernel': ['poly']}])

In [24]:
gsv.best_params_

{'C': 15, 'gamma': 100, 'kernel': 'poly'}

In [25]:
gsv.best_score_

0.9733449477351916

In [28]:
clf=SVC(C=15,gamma=100)

In [29]:
clf.fit(X_train,y_train)

SVC(C=15, gamma=100)

In [30]:
y_pred=clf.predict(X_test)

In [31]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [32]:
acc=accuracy_score(y_test,y_pred)*100

In [33]:
print(acc)

80.76923076923077


In [36]:
print(confusion_matrix(y_test,y_pred))

[[ 0 20]
 [ 0 84]]


In [37]:
clf_lin=SVC(kernel='linear')

In [38]:
clf_lin.fit(X_train,y_train)

SVC(kernel='linear')

In [39]:
y_pred=clf_lin.predict(X_test)

In [40]:
acc=accuracy_score(y_test,y_pred)*100

In [41]:
acc

98.07692307692307

In [42]:
clf_pol=SVC(kernel='poly')

In [43]:
clf_pol.fit(X_train,y_train)

SVC(kernel='poly')

In [44]:
y_pred2=clf_pol.predict(X_test)

In [45]:
y_pred2

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [46]:
acc=accuracy_score(y_test,y_pred2)*100

In [47]:
acc

82.6923076923077

In [48]:
clf_rbf=SVC(kernel='rbf')

In [49]:
clf_rbf.fit(X_train,y_train)

SVC()

In [50]:
y_pred2=clf_rbf.predict(X_test)

In [51]:
acc=accuracy_score(y_test,y_pred2)*100

In [52]:
acc

81.73076923076923